name: ai-big-data-cemfi
channels:
  - conda-forge
dependencies:
  - python
  - jupyter
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - matplotlib
  - seaborn
  - pytorch
  - xlrd
  - spacy
  - wordcloud
  - gensim
  - pyldavis
  - huggingface_hub=0.36.0
  - transformers
  - sentence-transformers
  - ollama
  - openai
  - pydantic
  - pip
  - pip:
      - sdmx1
      - pyfredapi
      - setuptools
      - wheel
      - spacytextblob
      - 'markitdown[all]'
